[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run chatbot.py --server.address 0.0.0.0 --server.port $PORT --theme.base light --theme.primaryColor '#FF8C00' --server.enableCORS false --server.enableXsrfProtection false"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Python Configuration
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# Streamlit Configuration
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
STREAMLIT_SERVER_ENABLE_CORS = "false"
STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION = "false"

# Application Configuration
ENVIRONMENT = "production"

# ChromaDB Configuration
CHROMA_DB_IMPL = "duckdb+parquet"
ANONYMIZED_TELEMETRY = "false"

# Memory and Performance
MALLOC_TRIM_THRESHOLD = "100000"

[build.environment]
# Build-time optimizations
NIXPACKS_PYTHON_VERSION = "3.11"